### ISSUE TITLE
mediatype unknown throws error

### ISSUE THREAD

**Issue by Venipa** [NovusTheory/xosms#13]
**Describe the bug**
[Window Title]
Error

[Main Instruction]
A JavaScript error occurred in the main process

[Content]
Uncaught Exception:
Error: internal error in Neon module: Failed to get DisplayUpdater.Type: Error { code: 0x80070057, message: "The media type specified is not valid.  Please specify either MediaPlaybackType_Music, MediaPlaybackType_Video, or MediaPlaybackType_Image.", win32_error: 87 }
    at MediaServiceProvider.set mediaType [as mediaType] (E:\git\ytmdesktop2\node_modules\xosms\dist\binding.js:70:16)
    at Object.__handleTrackMediaOSControlChange (webpack:///./src/app/plugins/mediaControlProvider.plugin.ts?:89:39)
    at IpcMainImpl.func (webpack:///./src/app/utils/onIpcEvent.ts?:41:47)
    at IpcMainImpl.emit (events.js:327:22)
    at IpcMainImpl.EventEmitter.emit (domain.js:467:12)
    at Object.__onActiveTrack (webpack:///./src/app/plugins/trackProvider.plugin.ts?:53:62)
    at IpcMainImpl.func (webpack:///./src/app/utils/onIpcEvent.ts?:41:47)
    at IpcMainImpl.emit (events.js:315:20)
    at IpcMainImpl.EventEmitter.emit (domain.js:467:12)
    at Object.eval (webpack:///./src/app/plugins/settingsProvider.plugin.ts?:110:66)

webpack:///./src/app/plugins/mediaControlProvider.plugin.ts?:89:39:
![image](https://user-images.githubusercontent.com/17952364/170387462-20bc2eed-f1d0-4271-b5f0-d5435430ecd1.png)

**To Reproduce**
1. set mediatype to unknown

**Expected behavior**
unknown to be set (or removed the option)

**Desktop (please complete the following information):**
 - OS: Windows 11
 - Browser electron
 - Version 12.0.1

**Xosms:**
- Version 0.2.0

**Comment by dm3ch** [comment]
@NovusTheory would API raise an error if there would be null or something else.

It seems quite confusing, that using the same cross-platform lib you can create an error using some of the enum values on specific platform. Maybe it would be better to set some default value (Music for example) to prevent rising of an error?

**Comment by NovusTheory** [comment]
That is true that it could be confusing. But unfortunately some platforms either play nice or they don't and as seen here Windows will not play nice and unfortunately likely won't let you set it to null or Unknown but Windows will provide Unknown if the developer has never set the media type yet.

Is there a better alternative to this? Xosms initial design was made after Windows but there's a lot of variances in the ways other operating systems do their media service that it makes it a bit weird to work with as some allow for one thing and some don't. Passing unknown could work perfectly fine for other systems but as evident here it doesn't work for Windows.

I do not think setting a default value is the best solution here as it becomes confusing very fast to the developer why their media type isn't being properly set. Would a better solution be to provide an API in xosms to check what APIs, values, or other are supported in the current operating system so the developer can work around those? This is more of just an unfortunate circumstance of supporting cross platform and you'll always have OS specific quirks.

**Comment by NovusTheory** [comment]
In the next version Xosms will now explicitly throw with an error message stating you cannot use the `Unknown` enum value for any enums with it. Additionally if the enum value specified is not valid e.g. the operating system doesn't support it or the value just isn't supported yet then it will throw an error instead of panicking the thread which it used to do.

I'll keep this issue open until it's merged into main and released

**Comment by NovusTheory** [comment]
Closing as the above is merged now
