### ISSUE TITLE
MacOS memory leaking

### ISSUE THREAD

**Issue by dm3ch** [NovusTheory/xosms#14]
**Describe the bug**
A memory leaking indefinitely in mac os.

**To Reproduce**
1. Run setting random Title in infinite loop.
2. Measure memory usage during run time.

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Xosms:**
- Version [e.g. 1.0.0]

**Additional context**

**Comment by NovusTheory** [comment]
I'm going to close this with the transition being made to rewrite the library in 0.5 and from before with 0.4 where I rewrote the macOS bindings to be swift which will later be reintroduced again in 0.5 I feel like this would no longer be an issue and I'm going to close it in favor of a new issue being opened when the time comes again.
