### ISSUE TITLE
Failed to get DisplayUpdater.MusicProperties

### ISSUE THREAD

**Issue by Venipa** [NovusTheory/xosms#19]
**Describe the bug**
upon setting albumArtist i get an exception

**To Reproduce**
1. Set albumArtist to `test's`

**Expected behavior**
No exception, or handled exception

**Screenshots**

![image](https://user-images.githubusercontent.com/17952364/182197558-e062373a-f33a-4dbb-bb4a-c8bdf67476aa.png)
![image](https://user-images.githubusercontent.com/17952364/182198117-efa431f5-2e2b-487b-93fc-659e2caf9649.png)

**Desktop (please complete the following information):**
 - OS: Windows 11 21h2 (Build 22000.795)
 - Browser: Electron 
 - Version: v19 (Chrome 104)

**Xosms:**
- Version: 0.3.0

**Comment by NovusTheory** [comment]
Going to close this as it's for an older version and before the rewrite
